import React, { SetStateAction } from "react";

export const language = {
    english: {
        king: "King",
        officer: "Officer",
        pawn: "Pawn",
        onlyKingDowned: "Only the king is downed",
        caromBalls: "Carom balls",
        alianBall: "Alien ball",
        kingAndFourPawnsKnockedDown:
            "The king and 4 pawns are knocked down at the same time",
        allPinsKnockedDown: "All the pins are knocked down at the same time",
        fiveCaromBalls:
            "The player made five carom balls in a row without gaining other point",
        bothSightingBallsScored:
            "As a result of the impact, both sighting balls are scored",
        ballJumedOffTable: "Ball jumped off",
        cueBallNotTouchSingleAimingBall: "Cue ball did't touch an aiming ball",
        cueBallFallsIntoPocket: "Cue ball fell into the pocket",
        touchingAimingBallWithCue: "Touching the aiming ball with the cue",
        listGames: "List of your games (view details)",
        umcompletedGame: "you have uncompleted games",
        emptyGamesList: "list of your games is empty",
        players: "players",
        welcome: "Welcome to",
        startNewGame: "Start a new game",
        letsGo: "Let's go",
        registration: "Players registration",
        addPlayer: "add player",
        back: "back",
        next: "next",
        nameAlreadyExists: "this name already exists",
        lettersOnly: "use letters only",
        noMore: "no more than ",
        letters: " letters",
        player: "player",
        enterName: "enter your name",
        atLeast: "at least ",
        gameSetup: "The game setup",
        initialPlayersPoints: "Initial points of the players:",
        points: "Points:",
        penalties: "Penalties:",
        reset: "Reset settings",
        orderInGame: "order in game:",
        victory: "victory",
        settingsGame: "Settings of the game",
        playersPoints: "Points of the players:",
        gamePoints: "Points of the game:",
        nextToGame: "next to game",
        penaltiesGame: "Game penalties:",
        downedPinsPenalties: "Downed pins penalties:",
        aproachPoints: "Aproach points: ",
        impactPoints: "Impact points: ",
        recordImpact: "record the impact",
        exitGame: "exit the game",
        commitApproach: "commit the approach",
        menu: "Menu",
        exchangeRate: "exchange rate",
        currency: "currency",
        cancel: "cancel",
        units: "units",
        code: "code",
        course: "course",
        exchangeRatesBankBelarus:
            "Exchange rates of the National Bank of Belarus on ",
        forToday: "for today",
        onDate: "on the date",
    },
    russian: {
        king: "Король",
        officer: "Офицер",
        pawn: "Пешка",
        onlyKingDowned: "Сбит только король",
        caromBalls: "Карамболь",
        alianBall: "Чужой шар",
        kingAndFourPawnsKnockedDown: "Сбиты одновременно король и четыре пешки",
        allPinsKnockedDown: "Сбиты одновременно все кегли",
        fiveCaromBalls:
            "Игрок «сделал» подряд пять карамболей, не набирая при этом других очков",
        bothSightingBallsScored:
            "В результате удара забиты оба прицельных шара",
        ballJumedOffTable: "Шар выскочил со стола",
        cueBallNotTouchSingleAimingBall: "Биток не коснулся прицельного шара",
        cueBallFallsIntoPocket: "Биток падает в лузу",
        touchingAimingBallWithCue: "Касание кием прицельного шара",
        listGames: "Список игр (посмотреть подробности)",
        umcompletedGame: "у вас есть незавершенные игры",
        emptyGamesList: "у вас нет истории игр",
        players: "игроки",
        welcome: "Добро пожаловать в",
        startNewGame: "Начать новую игру",
        letsGo: "старт",
        registration: "Регистрация игроков",
        addPlayer: "добавить",
        back: "назад",
        next: "вперед",
        nameAlreadyExists: "такое имя уже есть",
        lettersOnly: "используйте только буквы",
        noMore: "не более ",
        letters: " символов",
        player: "имя игрока",
        enterName: "введите имя",
        atLeast: "не менее ",
        gameSetup: "Настройка параметров игры",
        initialPlayersPoints: "Начальные очки игроков:",
        points: "Очки:",
        penalties: "Штрафы:",
        reset: "Сброс",
        orderInGame: "очередность",
        victory: "победа",
        settingsGame: "Параметры игры",
        playersPoints: "Очки игроков:",
        gamePoints: "Призовые очки:",
        nextToGame: "начало игры",
        penaltiesGame: "Штрафные очки:",
        downedPinsPenalties: "Штраф за сбитые кегли:",
        aproachPoints: "Очки за подход: ",
        impactPoints: "Очки за удар: ",
        recordImpact: "записать удар",
        exitGame: "выйти из игры",
        commitApproach: "фиксация подхода",
        menu: "Меню",
        exchangeRate: "курсы валют",
        cancel: "отмена",
        currency: "валюта",
        units: "ед.",
        code: "код",
        course: "курс",
        exchangeRatesBankBelarus: "Курсы валют Национального Банка РБ на ",
        forToday: "на сегодня",
        onDate: "на дату",
    },
};

type ILanguage = typeof language.english;

interface ILanguageContext {
    languageTheme: ILanguage;
    setLanguageTheme: React.Dispatch<SetStateAction<ILanguage>>;
}

export const LanguageContext = React.createContext<ILanguageContext>({
    languageTheme: language.russian,
    setLanguageTheme: () => {},
});
